### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [zlebruh/fetch-her#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by zlebruh** [comment]
I actually wrote this thing in TypeScript but did not want to maintain two different packages.

What, exactly, would your solution involve? Can't be just a file with interfaces, right?

I'd do whatever it takes to easy your journey.

**Comment by geopic** [comment]
All I would add would be a file that informs the TypeScript extension (that a TS developer would have installed in their IDE) of the required data types of arguments, the types of values that are returned from functions and so on. It's a kind of TS enforcement utility for this library that's written in JS and subsequently has no strict type enforcement. So yeah, it'll just be a file :wink:. With interfaces, maybe, maybe not (interfaces are not always needed).

**Comment by zlebruh** [comment]
Sounds good. Do your voodoo magic so that I may learn. Looking forward to your contribution.

Not entirely how all this works yet. Anything I can/should do?

**Comment by geopic** [comment]
> Anything I can/should do?

I'll let you know if I need anything :smiley:
